sudo: required # ask for super user permissions
services:
  - docker # ask to insstall a copy of docker into the container

before_install: # commands that are exec before the tests
  - "docker build -t danielcordeirodev/docker-react -f Dockerfile.dev ."

script: # commands to run the test suite
  - "docker run -e CI=true danielcordeirodev/docker-react yarn test -- --coverage"

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-514197381319"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
